### CREATE MOVIE
POST {{URL}}/movie
Authorization: Bearer {{TOKEN}}

### UPDATE MOVIE
PUT {{URL}}/movie/6891e5684b389b0313dbfd30
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "poster": "https://example.com/posters/avengers-endgame-small.jpg",
  "bigPoster": "https://example.com/posters/avengers-endgame-big.jpg",
  "title": "Мстители: Финал",
  "slug": "avengers-endgame",
  "parameters": {
    "year": 2019,
    "duration": 181,
    "country": "США"
  },
  "videoUrl": "https://example.com/videos/avengers-endgame.mp4",
  "genres": ["6891d54d880af8d3eefa3657"],
  "actors": ["6891d569880af8d3eefa365c"],
  "isSendTelegram": true
}

###BY-SLUG
GET {{URL}}/movie/by-slug/leonardo-dicaprio

###BY-ID
GET {{URL}}/movie/688b81d7ae849efd56c6bc33
Authorization: Bearer {{TOKEN}}

### GET ALL
GET {{URL}}/movie